# Generated by Django 3.1.3 on 2020-11-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avocado',
            name='average_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='avocado',
            name='region',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='avocado',
            name='type',
            field=models.CharField(choices=[('conventional', 0), ('organic', 1)], max_length=15),
        ),
    ]
